# Generated by Django 4.2.2 on 2024-08-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsettings_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('change_mailingsettings_setting_status', 'Can change mailingsettings setting_status')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
